### ISSUE TITLE
need a newer build :p

### ISSUE THREAD

**Issue by jonatjano** [noseglid/autocomplete-java-minus#15]
Hi,
When i downloaded your package I got this error
"Some installed packages could not be loaded because they contain native modules that were compiled for an earlier version of Atom."

Here the details : 
"build@unknown – Cannot find module '/home/jonatjano/.atom/packages/autocomplete-java-minus/node_modules/oniguruma/build'"

I am using atom 1.19.0 on debian 9 (stretch)

If the error doesn't come from this but another thing that i need to do or if you need more details about my config don't hesitate to say it ;)

Thank for your work 👍

**Comment by jonatjano** [comment]
My bad didn't see the "rebuild" button ^^

**Comment by noseglid** [comment]
👍
